name: MacOS Build

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache-dependency-path: ./app/package-lock.json
        node-version: 20
        cache: 'npm'
    - run: npm ci
      working-directory: ./app
    - run: npm run build
      working-directory: ./app
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
